import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "./Navbar";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const inter = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookie = cookies();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="_next">
          <Navbar cookie={cookie.get("session_id")?.value as string} />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
